### ISSUE TITLE
Training with my own datasets

### ISSUE THREAD

**Issue by ylyenjoy** [MCG-NJU/TDN#14]
I follow the steps made my own datasets with kinetics400 format,one GPU, I set batch_size=16,and but i met a question when trained,this is error code:
train_loader: <torch.utils.data.dataloader.DataLoader object at 0x7f90f6298460>
Traceback (most recent call last):
  File "main.py", line 361, in <module>
    main()
  File "main.py", line 211, in main
    train_loss, train_top1, train_top5 = train(train_loader, model, criterion, optimizer, epoch=epoch, logger=logger, scheduler=scheduler)
  File "main.py", line 261, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/shtf/ysir/pycharmprojects/TDN-main/ops/dataset.py", line 162, in __getitem__
    video_list = decord.VideoReader(video_path)
UnboundLocalError: local variable 'video_path' referenced before assignment

Traceback (most recent call last):
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/shtf/anaconda3/envs/py38/bin/python', '-u', 'main.py', '--local_rank=0', 'kinetics', 'RGB', '--arch', 'resnet50', '--num_segments', '8', '--gd', '20', '--lr', '0.02', '--lr_scheduler', 'step', '--lr_steps', '50', '75', '90', '--epochs', '100', '--batch-size', '16', '--wd', '1e-4', '--dropout', '0.5', '--consensus_type=avg', '--eval-freq=1', '-j', '4', '--npb']' returned non-zero exit status 1
I have no idea about this ,thank you

**Comment by yztongzhan** [comment]
Can you show the structure of your K400 dataset and the annotation file?

**Comment by ylyenjoy** [comment]
OK, My dataset have 2 classes,so there are two folders to store my videos,and my annotation file like this:
/home/shtf/ysir/datasets/turn/normal/108.mp4 0
/home/shtf/ysir/datasets/turn/normal/28.mp4 0

**Comment by yztongzhan** [comment]
Sorry, you can directly modify this line https://github.com/MCG-NJU/TDN/blob/100c9ed98b8708ea1349318924edbd6c4fed99c5/ops/dataset.py#L162 
with `video_list = decord.VideoReader(directory) `

**Comment by ylyenjoy** [comment]
OK,I trid this,it works,but I met anothor question,this time I trained my network without command "--master_port 12347" becase of one GPU caused CUDA out of memery,this is error code:
Traceback (most recent call last):
  File "main.py", line 360, in <module>
    main()
  File "main.py", line 211, in main
    train_loss, train_top1, train_top5 = train(train_loader, model, criterion, optimizer, epoch=epoch, logger=logger, scheduler=scheduler)
  File "main.py", line 267, in train
    prec1, prec5 = accuracy(output.data, target, topk=(1, 5))
  File "/home/shtf/ysir/pycharmprojects/TDN-main/ops/utils.py", line 71, in accuracy
    _, pred = output.topk(maxk, 1, True, True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26
Traceback (most recent call last):
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/shtf/anaconda3/envs/py38/bin/python', '-u', 'main.py', '--local_rank=0', 'kinetics', 'RGB', '--arch', 'resnet50', '--num_segments', '8', '--gd', '20', '--lr', '0.02', '--lr_scheduler', 'step', '--lr_steps', '50', '75', '90', '--epochs', '100', '--batch-size', '4', '--wd', '1e-4', '--dropout', '0.5', '--consensus_type=avg', '--eval-freq=1', '-j', '4', '--npb']' returned non-zero exit status 1
thanks

**Comment by yztongzhan** [comment]
Consider that you only have one GPU, we recommend that you run the test using our pre-trained model.

**Comment by ylyenjoy** [comment]
OK,let me have a try

**Comment by ylyenjoy** [comment]
Now I tried test using the pre-trained model [https://drive.google.com/drive/folders/1p7NC4JjxaLzwfj1JUa4kkHd_KZBxBBYR?usp=sharing],but it deosn't seem can load correctly,and my command is "CUDA_VISIBLE_DEVICES=0 python3 test_models_three_crops.py  kinetics --archs='resnet50' --weights /home/shtf/ysir/pycharmprojects/TDN-main/best.pth.tar --test_segments=8 --test_crops=3 --batch_size=4 --full_res --gpus 0 --output_dir /home/shtf/ysir/pycharmprojects/TDN-main/output -j 4 --clip_index 4"
and this is error code:
kinetics: 400 classes

    Initializing TSN with base model: resnet50.
    TSN Configurations:
        input_modality:     RGB
        num_segments:       8
        new_length:         1
        consensus_module:   avg
        dropout_ratio:      0.8
        img_feature_dim:    256
            
=> base model: resnet50
Traceback (most recent call last):
  File "test_models_three_crops.py", line 129, in <module>
    net.load_state_dict(base_dict)
  File "/home/shtf/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TSN:
	Missing key(s) in state_dict: "base_model.conv1.weight", "base_model.conv1.bias", "base_model.bn1.weight", "base_model.bn1.bias", "base_model.bn1.running_mean", "base_model.bn1.running_var", "base_model.conv1_temp.weight"...

**Comment by yztongzhan** [comment]
Hi @ylyenjoy, I have fix this bug, you can `git pull` and test again. 
Besides, this [pre-trained model](https://drive.google.com/drive/folders/1p7NC4JjxaLzwfj1JUa4kkHd_KZBxBBYR?usp=sharing) you download is `num_segments = 16`, you need to modify the test script according to this.
Thanks!
